# The restrictions that you apply at the pod level applies to all the containers
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod
spec:
  securityContext:
    runAsUser: 1000 # all processes run as user 1000
    runAsGroup: 3000 # primary group id for all processes within the containers
    fsGroup: 2000 # suplementary group id, also it's the owner of the volumes and any files in that volumes
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"