# Define a service account and automount the api credentials
apiVersion: v1
kind: Pod
metadata:
  name: init-container
automountServiceAccountToken: false
spec:
  containers:
  - name: app-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false