apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-front
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: front-app
  minReplicas: 5
  maxReplicas: 40
  targetCPUUtilizationPercentage: 75