apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "admin" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: admins-global
subjects:
- kind: Group
  name: admins # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "dev" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: developer-global
subjects:
- kind: Group
  name: devs # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "dev" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: reader-global
subjects:
- kind: Group
  name: reader # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io