apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-front
  namespace: k8s-deploy
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app-front
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
