apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-front
  labels:
    app: front
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: app-front
        image: paubarranca/docker-multi-site-apache 
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "300M"
            cpu: "300m"
          limits:
            memory: "500M"
            cpu: "500m"
        
---

apiVersion: v1
kind: Service
metadata:
  name: svc-app-front
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: front
    type: NodePort

