apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-anti-affinity
spec:
  selector:
    matchLabels:
      app: web-store
  replicas: 3
  template:
    metadata:
      labels:
        app: web-store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-store
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: web-store
          image: nginx
          resources:
              limits:
                memory: "128Mi"
                cpu: "100M"