apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-app
  labels:
    app: front
    env: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: front
        env: dev
    spec:
      containers:
      - name: front-app
        image: paubarranca/debian-apache-php:v1
        livenessProbe:
          exec:
            command:
              - /usr/bin/php
              - /usr/local/scripts/health-check.php
            initialDelaySeconds: 5
            periodSeconds: 5
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "600M"
            cpu: "600m"
          limits:
            memory: "1GB"
            cpu: "1GB"
      priorityClassName: low-priority
      volumes:
      - name: front-app-dev
        persistentVolumeClaim:
          claimName: front-app-dev
              
---

apiVersion: v1
kind: Service
metadata:
  name: front-app-dev
  labels:
    app: front
    env: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: front
    env: dev