apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-pv
spec:
  volumes:
    - name: pv-redis
      persistentVolumeClaim:
        claimName: pvc-redis
  containers:
    - name: redis-pv
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/lib/redis/data"
          name: pv-redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  labels:
    type: redis-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/redis/data/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi