apiVersion: v1
kind: PersistentVolume
metadata:
  name: front-app-pre
  labels:
    app: front
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/httpdocs"