kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: front-app-pre
  labels:
    app: front
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd