apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /var/lib/redis/data/
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumeClaimTemplates:
  volumes:
  - name: redis-storage
    emptyDir: {}