apiVersion: v1
kind: Pod
metadata:
  name: redis-app
  env: test
spec:
  containers:
    - name: redis-app
      image: paubarranca/redis:v1
      env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-pass
            key: password
      resources:
        requests:
          memory: "250M"
          cpu: "250m"
        limits:
          memory: "400M"
          cpu: "500m"
  restartPolicy: Always
  priorityClassName: low-priority