apiVersion: v1
kind: Pod
metadata:
  name: sec-env-pod
spec:
  containers:
    - name: sec-env-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysecret
              key: password
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"

---
# To encode the values before using them:    echo "really_secret_value1" | base64
# To decode:    echo "cmVhbGx5X3NlY3JldF92YWx1ZTEK" | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm