# In the volume, the mode specify the filesystem permissions that the secrets will have
# default: 0644
# 256 = 0400
# 511 = 0777
apiVersion: v1
kind: Pod
metadata:
  name: sec-volume-pod
spec:
  containers:
  - name: sec-volume-container
    image: redis
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/foo"
    resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
      mode: 256

---
# To encode the values before using them:    echo "really_secret_value1" | base64
# To decode:    echo "cmVhbGx5X3NlY3JldF92YWx1ZTEK" | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm