apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
    
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.9.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"