apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: nginx
subsets:
- addresses:
  - ip: 10.16.8.149
  ports:
  - port: 80
    protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.9.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"